### ISSUE TITLE
Testbed client setup for Kubernetes cluster

### ISSUE THREAD

**Issue by fpaparoni** [ISAITB/gitb#67]
I'm trying to create a setup of ITB in a Kubernetes cluster. I created different resources to map everything required by the standard setup of ITB. I'm using the official images (isaitb/gitb-ui and isaitb/gitb-srv) and when I try to deploy in a cluster I receive an error from the git-ui container

```
22/07/2024 12:53:11 INFO  org.eclipse.jetty.server.Server - jetty-11.0.20; built: 2024-01-29T21:04:22.394Z; git: 
922f8dc188f7011e60d0361de585fd4ac4d63064; jvm 17.0.11+9
22/07/2024 12:53:11 ERROR o.a.c.t.h.JettyHTTPServerEngine - Could not start Jetty server on port 9,090: Failed to bind to gitb-ui/10.3.53.53:9090
22/07/2024 12:53:11 INFO  org.eclipse.jetty.server.Server - Stopped Server@44f338ec{STOPPING}[11.0.20,sto=0]
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: WebServiceException: Fault: Could not start Jetty server on port 9,090: Failed to bind to gitb-ui/10.3.53.53:9090
  at hooks.PostStartHook.<init>(PostStartHook.scala:32)
  at modules.Module.configure(Module.scala:24)
      \_ installed by: Modules$OverrideModule -> modules.Module
  while locating hooks.PostStartHook

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Fault:                  "org.apache.cxf.interceptor.Fault"
Modules$OverrideModule: "com.google.inject.util.Modules$OverrideModule"
WebServiceException:    "jakarta.xml.ws.WebServiceException"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:176)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: jakarta.xml.ws.WebServiceException: org.apache.cxf.interceptor.Fault: Could not start Jetty server on port 9,090: Failed to bind to gitb-ui/10.3.53.53:9090
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:373)
	at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:255)
	at org.apache.cxf.jaxws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:130)
	at jakarta.xml.ws.Endpoint.publish(Endpoint.java:224)
	at hooks.PostStartHook.initialiseTestbedClient(PostStartHook.scala:240)
	at hooks.PostStartHook.onStart(PostStartHook.scala:43)
	at hooks.PostStartHook.<init>(PostStartHook.scala:36)
	at hooks.PostStartHook$$FastClassByGuice$$65aba08.GUICE$TRAMPOLINE(<generated>)
	at hooks.PostStartHook$$FastClassByGuice$$65aba08.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	... 9 more
Caused by: org.apache.cxf.interceptor.Fault: Could not start Jetty server on port 9,090: Failed to bind to gitb-ui/10.3.53.53:9090
	at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngine.addServant(JettyHTTPServerEngine.java:492)
	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.activate(JettyHTTPDestination.java:184)
	at org.apache.cxf.transport.AbstractObservable.setMessageObserver(AbstractObservable.java:53)
	at org.apache.cxf.binding.AbstractBindingFactory.addListener(AbstractBindingFactory.java:95)
	at org.apache.cxf.binding.soap.SoapBindingFactory.addListener(SoapBindingFactory.java:894)
	at org.apache.cxf.endpoint.ServerImpl.start(ServerImpl.java:130)
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:364)
	... 26 more
Caused by: java.io.IOException: Failed to bind to gitb-ui/10.3.53.53:9090
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.eclipse.jetty.server.Server.doStart(Server.java:398)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngine.addServant(JettyHTTPServerEngine.java:481)
	... 32 more
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339)
	... 47 more
```

I saw the official gitb-ui image is using the following property for TESTBED_CLIENT_URL

https://github.com/ISAITB/gitb/blob/d16d4d6638b84b4474f9f1d6e0cafeeebc121cd9/etc/docker/gitb-ui/Dockerfile#L5C1-L5C57

I don't know how ITB works internally but it creates a WS Endpoint using this URL, however in the Kubernetes cluster the git-ui URL is related to service resource (not to the deployment/pod one) so the container throws this error. In order to understand when it is used this URL I created another gitb-ui Docker image using the following setup

`ENV TESTBED_CLIENT_URL http://gitb-ui:9090/TestbedClient`

If I try to deploy ITB using this image it seems to work, but when I try to create a first test suite I receive this error from gitb-srv

```
22/07/2024 20:47:19 INFO  com.gitb.engine.SessionManager - [] SessionManager has been initialized...
22/07/2024 20:47:20 INFO  com.gitb.tbs.Application - [] Started Application in 4.631 seconds (process running for 5.333)
java.net.ConnectException: ConnectException invoking http://localhost:9090/TestbedClient?wsdl: Connection refused
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1452)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1433)
	at org.apache.cxf.transport.http.HttpClientHTTPConduit$HttpClientWrappedOutputStream.close(HttpClientHTTPConduit.java:511)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:717)
	at org.apache.cxf.transport.http.HttpClientHTTPConduit.close(HttpClientHTTPConduit.java:115)
	at org.apache.cxf.transport.TransportURIResolver.resolve(TransportURIResolver.java:134)
	at org.apache.cxf.wsdl11.CatalogWSDLLocator.getBaseInputSource(CatalogWSDLLocator.java:71)
	at org.apache.cxf.wsdl11.AbstractWrapperWSDLLocator.getBaseInputSource(AbstractWrapperWSDLLocator.java:70)
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:225)
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165)
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:169)
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:160)
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:128)
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82)
	at jakarta.xml.ws.Service.<init>(Service.java:82)
	at com.gitb.tbs.TestbedClient_Service.<init>(TestbedClient_Service.java:50)
	at com.gitb.tbs.impl.TestbedServiceCallbackHandler$WSAddresingProperties.<init>(TestbedServiceCallbackHandler.java:99)
	at com.gitb.tbs.impl.TestbedServiceCallbackHandler.saveWSAddressingProperties(TestbedServiceCallbackHandler.java:52)
	at com.gitb.tbs.impl.TestbedServiceImpl.initiate(TestbedServiceImpl.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.performInvocation(JAXWSMethodInvoker.java:65)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:231)
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:84)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:74)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$2.run(ServiceInvokerInterceptor.java:126)
	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:131)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:233)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:207)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:159)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:224)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:216)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
```

So from what I can see this property is inherited from the gitb-srv and it's clear that this cannot work in this environment. Is there a way to setup a correct value for this URL in order to start ITB in a Kubernetes cluster?

**Comment by costas80** [comment]
Hi @fpaparoni. We have never deployed the ITB using Kubernetes but doing so should not create problems.

Having said this, I'm not following exactly what you did:

> I created another gitb-ui Docker image using the following setup

The ENV value you specify is the one that is already set by default in the Dockerfile, so I don't follow what customisation you did on top.

Regarding the gitb-srv error you see, this is not due to another configuration value that sets this URL again on gitb-srv. This is the callback address of the gitb-ui endpoint (the one listening on port 9090) that gitb-ui reads from it's configuration/environment and sets it as the SOAP Reply-To header as per WS Addressing. This is used as-is by gitb-srv (reading the value from the received SOAP header), so if this comes (incorrectly) as localhost it means that gitb-ui is not configured with the right environment variables (as its Dockerfile does).

In brief there's something going on with the environment variables you're setting. Maybe start up gitb-ui and before trying to run a test, just check the WS endpoints are correctly initialised by doing a GET on the WSDLs.

**Comment by costas80** [comment]
I thought about this on my end as well and came to the same conclusion you did @fpaparoni. To have a Kubernetes installation of the ITB we'd need to have two URLs for the ENV value we have been discussing, one "internal" to create the endpoint and one "external" that is reported to other components as the Reply-To address (basically to gitb-srv). You also summed this up in your first option:

> Duplicate the parameter to have separated values. But in that case, is it required to have a URL for publishing, or 0.0.0.0 can be enough?

I would keep the current variable as the "external" one, and introduce a new "internal" variable that if not set, defaults to the same value. The internal one could even be set to "localhost" I assume.

In hindsight this is quite simple a fix. Once tested we'll make it available on our [nightly build channel](www.itb.ec.europa.eu/docs/guides/latest/onboardingDevelopers/index.html#using-nightly-builds) and include it also in the next stable release.

**Comment by fpaparoni** [comment]
In the meanwhile I can confirm ITB works without problems inside Kubernetes cluster, using a single deployment (single pod, multiple containers). It isn't a production environment, but it can be used for a simple development environment.

**Comment by costas80** [comment]
Hi @fpaparoni. The update we discussed is now published on [nightly channel](https://github.com/ISAITB/gitb/issues/www.itb.ec.europa.eu/docs/guides/latest/onboardingDevelopers/index.html#using-nightly-builds). With this update, the `gitb-ui` container supports two environment variables as follows:

|Variable|Default value in published images|Description|
|---|---|---|
|`TESTBED_CLIENT_URL_INTERNAL`|`http://localhost:9090/TestbedClient`|The internal address at which the client endpoint is published within the container/pod.|
|`TESTBED_CLIENT_URL`|`http://gitb-ui:9090/TestbedClient`|The public address at which the client endpoint is published (e.g. called by `gitb-srv`).|

You could explicitly define these variables but you could also be ok with the default values. Can you confirm if this works for you once you've had a chance to test?

**Comment by fpaparoni** [comment]
Hi @costas80, I can confirm the update available in the nightly channel enables the deployment on the Kubernetes cluster. Using the default value for **TESTBED_CLIENT_URL_INTERNAL** it doesn't work, because it publishes on the localhost and not on the external network. Using the value **http://0.0.0.0:9090/TestbedClient** there is no problem.

**Comment by costas80** [comment]
Great to hear @fpaparoni. Thanks also for the `0.0.0.0` pointer. We should be able to use this as the default interface when running also in Docker or even without containers/pods. I'll test and update the nightly build if this indeed works as expected (let's keep this issue open until then).

**Comment by costas80** [comment]
Using `http://0.0.0.0:9090/TestbedClient` as the default value for `TESTBED_CLIENT_URL_INTERNAL` works like a charm in all deployment scenarios. The nightly image is now updated to use this as the default.

If you want @fpaparoni, you can now pull the latest nightly and remove your specific configuration for `TESTBED_CLIENT_URL_INTERNAL`. In a nutshell, the Test Bed images should now work out-of-the-box in Kubernetes.

Can you confirm that this works for you?

**Comment by fpaparoni** [comment]
I can confirm using the latest nightly and removing specific configuration for `TESTBED_CLIENT_URL_INTERNAL`, everything works
